basic.forever(function () {
    led.plot(1, 1)
    led.plot(4, 2)
    led.plot(3, 1)
    led.plot(2, 1)
    led.plot(4, 3)
    led.plot(4, 4)
    led.plot(3, 4)
    led.plot(2, 4)
    led.plot(1, 4)
    led.plot(0, 4)
    led.plot(0, 3)
    led.plot(0, 2)
    led.plot(2, 0)
})
